

info.configuration: Properties from configuration repo


# eureka settings
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${INT_EUREKA_HOST:http://localhost:8761/eureka/}
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 10
    preferIpAddress: true


# enable actuator endpoints 
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
